#!/usr/bin/env bash

set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export SEED_SKILL_GEN_LOSS_ENABLE=${SEED_SKILL_GEN_LOSS_ENABLE:-True}
export SEED_SKILL_GEN_LOSS_COEF=${SEED_SKILL_GEN_LOSS_COEF:-0.01}
export SEED_SKILL_GEN_MICRO_BATCH_SIZE_PER_GPU=${SEED_SKILL_GEN_MICRO_BATCH_SIZE_PER_GPU:-${SEED_SKILL_GEN_MICRO_BATCH_SIZE:-1}}
export SEED_SKILL_MODE=${SEED_SKILL_MODE:-step_only}
export SEED_SKILL_GEN_MAX_SAMPLES=${SEED_SKILL_GEN_MAX_SAMPLES:-all}
export SEED_SKILL_GEN_VALID_JSON_BONUS=${SEED_SKILL_GEN_VALID_JSON_BONUS:-0.0}
export SEED_SKILL_GEN_NON_EMPTY_SKILL_BONUS=${SEED_SKILL_GEN_NON_EMPTY_SKILL_BONUS:-0.0}
export SEED_SKILL_GEN_TOO_LONG_PENALTY=${SEED_SKILL_GEN_TOO_LONG_PENALTY:-0.0}
export SEED_SKILL_GEN_MAX_OUTPUT_CHARS=${SEED_SKILL_GEN_MAX_OUTPUT_CHARS:-1200}
export SEED_SKILL_GEN_REWARD_CLIP=${SEED_SKILL_GEN_REWARD_CLIP:-2.0}
export SEED_SKILL_GEN_FAILED_REWARD_MODE=${SEED_SKILL_GEN_FAILED_REWARD_MODE:-negate}
export EXPERIMENT_NAME=${EXPERIMENT_NAME:-seed_qwen2.5_3b_alfworld_step_skill_loss_base}

exec "$SCRIPT_DIR/run_alfworld_both_no_skill_loss_base.sh" "$@"
